import asyncio
from app.api.routes.agents import router
from fastapi import FastAPI
from fastapi.testclient import TestClient

app = FastAPI()
app.include_router(router, prefix="/api/agents")

# Mock the auth dependency
from app.api.routes import agents as agents_module
agents_module.get_current_active_user = lambda: None
agents_module.get_db = lambda: None

client = TestClient(app)

print("Testing demo endpoint with fallback to synthetic generator...")
print("=" * 60)

response = client.post("/api/agents/analyze/demo?risk_title=Ransomware%20Attack")
data = response.json()

print(f"Status: {response.status_code}")
print(f"Generated by: {data.get('generated_by', 'unknown')}")
print(f"Number of messages: {len(data.get('discussion', []))}")
print(f"\nFirst message: {data['discussion'][0]['agent']}: {data['discussion'][0]['message'][:60]}...")
print("\n✓ Endpoint is working with synthetic fallback")
